# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160711_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_content',
            name='video',
            field=models.FileField(upload_to='media/uploaded/%Y'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='media/uploaded/%Y'),
        ),
    ]
