# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poketmon', '0002_auto_20160716_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='catch_places',
            new_name='catched_places',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='catch_pokemons',
            new_name='catched_pokemons',
        ),
    ]
