# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poketmon', '0003_auto_20160716_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='level',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
