# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketmon', '0005_auto_20160718_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poketmon.Pokemon')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='catched_places',
        ),
        migrations.RemoveField(
            model_name='user',
            name='catched_pokemons',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AddField(
            model_name='capture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poketmon.User'),
        ),
    ]
